vich_uploader:
  metadata:
    type: attribute
  db_driver: orm
  mappings:
    images:
      uri_prefix: /uploads/images
      upload_destination: "%kernel.project_dir%/public/uploads/images"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
