vich_uploader:
  metadata:
    type: attribute
  db_driver: orm
  mappings:
    medias:
      uri_prefix: /uploads/medias
      upload_destination: "%kernel.project_dir%/public/uploads/medias"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
